### ISSUE TITLE
Why `*` is greedy like `**`?

### ISSUE THREAD

**Issue by lmvaibhavk** [ganbarodigital/go_glob#1]
I have a directory structure as follows:
`a1`, `a2`, `a3`, `a1/b1`, `a2/b2`.
When I run match using pattern `*`, I am expecting it to match only a1, a2, and a3 not the a1/b1, a2/b2.

Correct me if I am missing anything?

**Comment by stuartherbert** [comment]
Hi!

This is covered in the README, on the [section about extended globbing and globstars](https://github.com/ganbarodigital/go_glob/blob/develop/README.md#what-about-extended-globbing-globstars-and-glob_ignore).

This package doesn't support extended globbing at the moment, as the package only deals with string expansion. It isn't filesystem-aware at this time.
